### ISSUE TITLE
Make `winum-ignored-buffers` a regex

### ISSUE THREAD

**Issue by quicknir** [deb0ch/emacs-winum#11]
Or introduce a second variable, that is a regex, and make sure it is ignored. This is useful as some packages may need to spawn more than one buffer for operation, and thus may use numbering in ordering to ensure they are unique.

As a concrete example, this would help treemacs play nice in terms of window numbering, in spacemacs, see: https://github.com/syl20bnr/spacemacs/issues/9865#issuecomment-353903168.

**Comment by deb0ch** [comment]
If we can keep backward compatibility without adding an extra variable it is best.

If not possible, priority is to backward compatibility.

**Comment by deb0ch** [comment]
After discussing it with you a few days ago, your initial idea of a new variable seems to be the best.

Have you had time for it recently ?

**Comment by mpanarin** [comment]
@deb0ch @quicknir 
Hello!

I implented this feature in this PR https://github.com/deb0ch/emacs-winum/pull/22
please have a look!

**Comment by deb0ch** [comment]
Merged, finally ! **\o/** :tada:
