### ISSUE TITLE
I have a small issue with winum-select-window-0-or-10

### ISSUE THREAD

**Issue by ipetepete** [deb0ch/emacs-winum#12]
I use two computers for work, one is a Mac, the other Linux Mint. My Mac works as expected when I use winum-select-window-0-or-10, the first window is selected, on my Linux machine though, winum-select-window-0-or-10 always reports "No window numbered 10".

On my Linux machine, I've also noticed the windows seem to be indexed rather oddly. The first window can be switched to using **winum-select-window-0** _or_ 
 **winum-select-window-1** which is confusing becuase if I have my file tree (Treemacs) open, then the first buffer switches indexes to 2, which isn't that big of a deal, but it is annoying. 

Do you have any idea what is going on? I'm using the same configuration on both computers, and nothing is set to change the default settings for winum.

Any help would be appreciated.

Thanks!

[EDIT]

I just found out this is not a winum issue but a treemacs issue. Please Close.

**Comment by deb0ch** [comment]
Thanks for taking the time to report, and don't hesitate if you actually find issues with Winum ! 😁 

FYI, I think that with Github you can close issues that you opened yourself.
