### ISSUE TITLE
winum-mode is not idempotent

### ISSUE THREAD

**Issue by jabranham** [deb0ch/emacs-winum#17]
Evaluating `(winum-mode)` adds the window number to the mode line for each invocation rather than just once.

I think an easy fix would to check for `(unless <winum-already-in-modeline> <add-winum-to-modeline)` in ` winum--install-mode-line`

**Comment by syamajala** [comment]
I was really confused why the first window number i was seeing was 11. Its because of this bug.

**Comment by deb0ch** [comment]
Hopefully fixed in #18, don't hesitate to reopen / open a new issue if the problem happens again. thanks for reporting !
