### ISSUE TITLE
Symbol’s function definition is void: winum-assign-0-to-neotree

### ISSUE THREAD

**Issue by zhangjie2012** [deb0ch/emacs-winum#19]
winum version: `2.1.0`

config ref: https://github.com/deb0ch/emacs-winum#configuration-file-example

**Comment by deb0ch** [comment]
Ooops, it seems like a typo in the example. I will fix it whenever I have a moment (or go ahead and send a PR 😉)

Just replace `winum-assign-0-to-neotree-and` with `winum-assign-0-to-neotree` in the `defun` 😅 

Thanks for reporting !

**Comment by deb0ch** [comment]
Fixed ! 🎉
