### ISSUE TITLE
Using winum-assign-func to always a specific number for a specific buffer leads to error

### ISSUE THREAD

**Issue by Alexander-Miller** [deb0ch/emacs-winum#4]
I want that the window used in my own treemacs package always gets window number 10 since the window always stays in the same position and shouldn't interfere with the numbering of other windows when its visibility is toggled. To that end I use the following code:

    (with-eval-after-load 'winum
      (defun treemacs--window-number-zero ()
        (when (s-equals? (buffer-name) treemacs--buffer-name) 10))

      (when (boundp 'winum-assign-func)
        (setq winum-assign-func #'treemacs--window-number-zero)))

However this does not work as actually creating a treemacs window gives me the following error:

    Debugger entered--Lisp error: (args-out-of-range [nil nil] 10)
      winum--assign(#<window 36 on *Backtrace*> 10)
      #[(w) "\304!r\305\216\306	@\307\"\210r\310!q\210\n \211\205
      winum--update()

More generally this doesn't seem to be an issue neither with the buffer I'm building, nor the number I'm assigning, since I've tried copy-pasting the example function from the readme and had the same problem when assiging number 9 to the scratch buffer.

I'm running on spacemacs 0.200.9 and the newest winum pulled from melpa.

**Comment by Alexander-Miller** [comment]
Looks like the issue starts in `winum--update`:

    (puthash (selected-frame)
             (cons (make-vector (1+ winum--window-count) nil)
                   (make-hash-table :size winum--window-count))
             winum--frames-table)

The vector's size is the number of visible windows. When you have two windows and open up a third that always wants to be number 10 you'll have index out of bounds problems.

Maybe the assign function could check if the number is bigger than the windows vector and then create a new bigger vector? `vconcat` should be able to do the job.

**Comment by deb0ch** [comment]
Thanks for the heads up ! I was just starting to look at it a minute ago :smile_cat:

I was actually starting with the other issue you opened; if you have a fix don't hesitate to PR, I will try to merge it quickly.

**Comment by Alexander-Miller** [comment]
No PR yet, but if you do the other first I'll try my luck here.

**Comment by deb0ch** [comment]
Don't hesitate to try your luck for both of them, I actually don't have much time these days so I might be slow at fixing these things :smile_cat:

**Comment by Alexander-Miller** [comment]
Pulled the newest version, everythings going well. Will be taking a look at the second issue.

**Comment by deb0ch** [comment]
Great, thanks ! :thumbsup::sparkles:
