### ISSUE TITLE
Display of superscript 2

### ISSUE THREAD

**Issue by quicknir** [deb0ch/emacs-winum#9]
This shows in spacemacs but seems to come directly from this package? If not, I will close this issue and open it on spacemacs. Basically a superscript 2 is shown in which-key after hitting SPC, though the actual key that can be pressed on US keyboards is backtick. Can this be changed to a backtick? I don't know exactly how it works out on other keyboards but hopefully we can agree that backtick is a much more standard symbol than a superscript 2.

**Comment by deb0ch** [comment]
In my own version, that I updated maybe one or two weeks ago, what is shown by `which-key` is

```
`,² → select window by number
```
is that what you're talking about ? If yes, how come it's different between you and me ?

**Comment by quicknir** [comment]
Ah, that's weird, looking again more carefully I see the backtick and the 2 as separate entries. Though that's not the same as what you are showing me, either one of those is fine so I'll just close this. Sorry about the bother!

**Comment by deb0ch** [comment]
No worries, but that's weird because that's *exactly* what I'm getting:

![screenshot from 2017-06-06 23 08 51](https://user-images.githubusercontent.com/6248219/26852068-378c5046-4b0d-11e7-964c-8e703ee75ba3.png)

Are you not getting the same ? What have you got instead ?

**Comment by quicknir** [comment]
Mine is different, I'll send you a screenshot tonight from home. I'm probably a few weeks back on the package version if you think that might make a difference.

**Comment by deb0ch** [comment]
Most likely back on a version of two of `which-key` then, it is only after a rework of it's API that we were able to regroup together similar commands with different bindings
